dossier/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :attachments
  end

end

dossier/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dossier/app/models/attachment.rb
# == Schema Information
#
# Table name: attachments
#
#  id                     :integer          not null, primary key
#  file_name              :string
#  attachment_type        :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_id                :integer
#  file_name_file_name    :string
#  file_name_content_type :string
#  file_name_file_size    :integer
#  file_name_updated_at   :datetime
#

class Attachment < ApplicationRecord
  attr_accessor :file_name

  belongs_to :user, inverse_of: :attachments
  has_attached_file :file_name
  validates_attachment_content_type :file_name,
    content_type: { file_name_content_type: "application/pdf" }
end

dossier/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  email               :string
#  username            :string
#  avatar              :string
#

class User < ActiveRecord::Base
  has_many :attachments

end

dossier/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

dossier/app/controllers/attachments_controller.rb
require 'pry'
class AttachmentsController < ApplicationController


  def index
    @attachments = Attachment.all
  end
  def show
    @attachement = get_attachment
  end

  def new
    @user = User.find(params[:user_id])
    @attachment = @user.attachments.build
  end


  def create
    @user = User.find(params[:user_id])
    @attachment = Attachment.new(attachment_params)

    if @attachment.save
      redirect_to @attachment
     else
       render :action => 'new'
     end
  end

  def edit
    @attachment = get_attachment
  end
  def update
    @attachment = get_attachment
      if @attachment.update(attachment_params)
        redirect_to @attachment
      else
        render 'edit'
      end
  end
private

  def attachment_params
    params.require(:attachment).permit(:file_name, :attachment_type, :user_id)
  end

  def get_attachment
    Attachment.find(params[:id])
  end
end

dossier/app/controllers/users_controller.rb
require 'pry'

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = get_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to @user
      else
        render :action => 'new'
      end
  end

  def edit
    @user= get_user
  end

  def update
    @user= get_user
      if @user.update(user_params)
        redirect_to @user
      else
        render 'edit'
      end
  end


end
private

  def get_user
    User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email ,:avatar)
  end

dossier/app/helpers/application_helper.rb
module ApplicationHelper
end

dossier/app/helpers/attachments_helper.rb
module AttachmentsHelper
end

dossier/app/helpers/users_helper.rb
module UsersHelper
end

dossier/app/views/attachments/_form.html.erb
<h3><strong> Details</strong></h3>


<%= simple_form_for [@user, @attachment] do |f| %>
  <%= f.input :attachment_type %>
  <%= f.input :file_name, as: :file %>

  <%= f.submit "Submit" %>

  <% end %>

dossier/app/views/attachments/edit.html.erb
Edit Existing attachment

<%= render 'attachments/form' %>

dossier/app/views/attachments/index.html.erb
<table>
  <tr>
    <th>attachment Name</th>
    <th>Email</th>
  </tr>

<% @attachments.each do |attachment| %>
  <tr>
    <td><%=link_to attachment.file_name, attachment_path(attachment)%>
    </td>
    <td><%=attachment.attachment_type %></td>
  </tr>

  <% end %>
</table>

dossier/app/views/attachments/new.html.erb
Add a new attachment

<%= render 'attachments/form' %>

dossier/app/views/attachments/show.html.erb
<table>
  <tr>
    <th>attachment Name</th>
    <th>Email</th>
  </tr>

  <tr>
    <td><%= @attachment.file_name %></td>
    <td><%= @attachment.attachment_type %></td>
  </tr>


</table>
<%= link_to 'Edit', edit_attachment_path(@attachment) %>

dossier/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dossier</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

dossier/app/views/users/_form.html.erb
<h3><strong>User Details</strong></h3>


<%= simple_form_for @user do |f| %>
  <%= f.input :email %>
  <%= f.input :username %>
  <!-- <%= f.input :avatar, as: :file %> -->
  <%= f.submit "Submit" %>

  <% end %>

dossier/app/views/users/edit.html.erb
Edit Existing User

<%= render 'users/form' %>

dossier/app/views/users/index.html.erb
<table>
  <tr>
    <th>User Name</th>
    <th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%=link_to user.username, user_path(user)%>
    </td>
    <td><%=user.email %></td>
  </tr>

  <% end %>
</table>

dossier/app/views/users/new.html.erb
Add a new user

<%= render 'users/form' %>

dossier/app/views/users/show.html.erb
<table>
  <tr>
    <th>User Name</th>
    <th>Email</th>
  </tr>

  <tr>
    <td><%= @user.username %></td>
    <td><%= @user.email %></td>
  </tr>


</table>
<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Add a file', new_user_attachment_path(@user, @attachment) %>